# These are the development environment settings for the project (dev). Make settings changes
# here that are useful while developing the project.

# Set the logging level to DEBUG to get all messages
logging:
  level:
    root: INFO
